baseURL: "https://abrampers.github.io"
languageCode: "en-us"
title: "abram's blog"
theme: "anubis"

menu:
  main:
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 2
    - identifier: tags
      name: Tags
      title: Tags
      url: /tags/
      weight: 2
    - identifier: archive
      name: Archive
      title: Archive
      url: /posts/
      weight: 0

params:
  customCSS:
    - css/custom.css
  paginationSinglePost: true
  style: auto
  readMore: true

markup:
  highlight:
    style: dracula
