#+hugo_base_dir: .

* About
:PROPERTIES:
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: about
:END:

asdfadsf

* blog
:PROPERTIES:
:EXPORT_HUGO_SECTION: blog
:END:

** DONE Using org mode and ox-hugo to replace markdown in hugo workflow
CLOSED: [2020-11-16 Mon 17:54]
:PROPERTIES:
:EXPORT_FILE_NAME: using-org-mode-and-ox-hugo-to-replace-markdown-in-hugo-workflow
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2020-11-16 Mon 17:54]
:END:

asdfasdf

** DONE WWDC19: Best Dub-Dub ever!                         :tech:conference:
CLOSED: [2019-06-24 Mon 17:55]
:PROPERTIES:
:EXPORT_FILE_NAME: wwdc19-best-dub-dub-ever
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-06-24 Mon 17:55]
:END:
#+toc: headlines 1 local

This year, I’m very lucky to be one of the WWDC19 Scholarship Winner from Indonesia to attend Apple’s event of the year. It’s obviously the best Dub-Dub ever since it’s my first time here! Dub-Dub 19 is an event packed with awesome things and I’m going to tell my story from the complete beginning. Here we go!

#+caption: HMIF ITB @ WWDC19 (Nicho, Abram, and Faza)
#+name: fig__group_image
https://cdn-images-1.medium.com/max/6048/1*mMUmHriJt0p8Y2Z46gBZGw.jpeg

*** What is WWDC?

#+begin_quote
The Apple Worldwide Developers Conference (WWDC, also known as Dub Dub) is a conference held annually by Apple Inc. in San Jose, California. Apple uses the event to showcase its new software and technologies for software developers. Attendees can participate in hands-on labs with Apple engineers and attend in-depth sessions covering a wide variety of topics. — Wikipedia
#+end_quote

Enough from Wikipedia, for me, WWDC is an event where developers gather and obtain plenty of insights from Apple about their software. Even better, it’s an event where students (or recently graduated High School students) can apply and actually receive the scholarship to go to this event without spending a single penny.

*** WWDC Scholarship?

The **scholarship** term here means that Apple will get you the WWDC ticket for **free**. I repeat, **for free**.

To submit, we have to create a Swift Playground that can be experienced in 3 minutes in iPad’s Swift Playgrounds or Xcode’s Playground. After submission, application will be judged based on:

- Technical accomplishment
- Creativity of ideas
- Content of written response

**** Application

On a beautiful morning on Thursday, March 15, 2019 Apple announced that they had opened WWDC Scholarship Submission and that all submissions are meant to be submitted before Sunday, March 24, 2019 at 5.00 PM PDT. Wow, 7 days to work on the submission? **Challenge accepted**! I was quite surprised because they only gave us 7 days to work on the submission while previously the submission was up to two weeks long.

At first, I had an idea to create a real-time style transfer application in Swift Playground using UIKit, CoreML and probably camera for the real-time transfer, but after 5 days of working on it, the CoreML model decided to not cooperate. It always gave an error without any description. Frustrating.

This problem forced me to find something outstanding that works and was good enough to distinct me from other applicants. And some *Metal* struck my mind. “Why don’t I try to use [[https://developer.apple.com/metal/][Metal]] just like how I used OpenGL for my Computer Graphics assignment?” And after 2 sleepless nights, I did just that.

I’ve created a simple introduction to *Metal* using MetalKit named *Metalify*. Here's the [[https://github.com/abrampers/WWDC19-Submission][playground]] if you'd like to try it on your own.

#+caption: Scholarship email!
#+name: fig__email_image
https://cdn-images-1.medium.com/max/2544/1*O64rdYG16VbLC7NK_cnA9g.png

On another beautiful morning — Monday, April 15, 2019 — I received this email and my heart stopped for a second. Man! I got this. I was one of 350 students worldwide that got the scholarship. That was the best day of my college life yet 🤖.

As a scholarship winner, they told me that we would get free WWDC ticket, free lodging on the San Jose State University dorm, and free breakfast and lunch meal.

*** WWDC19

**** Swag

Fast forward to the Dub Dub week, we got to check in at the convention center and received some Dub Dub Swag for us to wear for the rest of the week. We got a reversible bomber jacket, a Scholarship Winner T-Shirt, and a few random pins including Indonesian Flag’s pin.

#+caption: Bomber jacket + small Tim Cook pin
#+name: fig__swag_image
https://cdn-images-1.medium.com/max/6048/1*7sfvKXgFy2aoxf9QTMHpKQ.jpeg

**** Scholarship kickoff

After checking in, all the scholarship winner were scheduled to attend scholarship kickoff where Esther Hare [@EEhare](https://twitter.com/eehare?lang=en) was there to give a little talk. She encouraged us to talk to as many people as we can, whether it’s fellow scholars, developers, or even Apple engineers. And the coolest thing here is that there were plenty of Apple engineers standing by for us to talk to. I was very excited since I never had any chance to get to meet, better yet, talk to the engineers that build Apple. Besides, there were plenty of food trucks and drinks all over the place..

#+name: fig__kickoff1_image
https://cdn-images-1.medium.com/max/12000/1*Vu7eITgS5sivMkDNtPuOPw.jpeg
#+caption: Beautiful weather @ Discovery Meadow with Indonesian scholarship winners
#+name: fig__kickoff2_image
https://cdn-images-1.medium.com/max/2250/1*ogZQRMEFWxEP8y9bQvQ2jw.jpeg

After the kickoff, a few of Indonesian scholars gather around and did a vlog about the Dub Dub. Here we go!

{{< youtube Ry0ezsPNt6I>}}

**** Keynote

The long awaited keynote was there and many people called this ‘the most packed WWDC Keynote ever’. This includes the announcement of the brand new Mac Pro, iPad OS, iOS 13, macOS Catalina and the SwiftUI & Combine which were the star for the rest of the week.

#+name: fig__keynote_image
#+attr_css: :width 75%
https://cdn-images-1.medium.com/max/3264/1*7IDRGBs7cyfjNYCb4eQ9Sg.jpeg

The most exciting part of the Keynote was the announcement of SwiftUI. There, Craig Federighi showed how [[https://developer.apple.com/documentation/swiftui][SwiftUI]], with its declarative traits + [[https://developer.apple.com/documentation/combine][Combine]] (Apple’s framework for Async programming) made multi-platform development seems so easy and fluid.

Project Catalyst had also brought huge possibilities since it enables developer to bring iPad Apps (built using UIKit) to run in Mac (typically built using AppKit). iPads can now be used as a *sidecar *to Mac. These two features will bring iPads closer to Macs and vice versa.

**** Scholarship Lounge

Scholars were given the privilege to chill and have a chit chat with fellow scholars throughout the week at the scholarship lounge. Here, we were given a wired 10MBps connection to try all the Betas they announced.

#+caption: Scholarship lounge: Our home
#+name: fig__lounge_image
https://cdn-images-1.medium.com/max/11228/1*HgGxRO1iodwpL36HH254nA.jpeg

**** Pro studio

#+caption: The recently announced Mac Pro
#+name: fig__prostudio_image
https://cdn-images-1.medium.com/max/8064/1*kmCk6hBke2b9lhluc6R04g.jpeg

All the Dub Dub attendee got the chance to visit the Pro Studio across the Convention Center to see the newly announced Mac Pro in action. In this building, they showcased a few workflows dome with the Mac Pro. Photo editing workflow, real-time 8K raw video rendering, creating music orchestra, and 3D Editing. Having seen all these things and as someone who didn’t really understand it, Mac Pro seemed like a real deal.

**** Sessions and Labs

For the rest of the week, there were plenty of sessions and labs conducted all over the Convention Center. Sessions are more like seminars conducted by Apple where they showcase best practices, reveal new features in more detail, and give a bit of demo. Labs are the place to go if you have a bug, question, or a feature request and give it right to the engineers that work on that particular feature. Awesome! We could actually ask the person who was in charge of the product. What a way to solve a bug.

#+name: fig__sessionlabs1_image
https://cdn-images-1.medium.com/max/8064/1*ZsvETrvysoT60qinnSB5yw.jpeg
#+name: fig__sessionlabs2_image
https://cdn-images-1.medium.com/max/8064/1*G0I23P7UxXG8_cbAa94LIA.jpeg
#+name: fig__sessionlabs3_image
https://cdn-images-1.medium.com/max/2000/1*lT-EgnL2S5TZziXPU5-j9w.jpeg

**** Games, Sporting Events, and WWDC Bash!

The sport activities was the High Intensity Interval Training by Aaptiv, WWDC 5K Run, and Yoga with Glo. They provided all the equipment for the training and let us have all the equipment. Note: They kinda gave us a $100 yoga mat LOL!

Throughout the week they conducted an AR game called SwiftStrike. It is a bowling game where the player had to hit down the opponent’s pin. At the end of the week, they conducted the SwiftStrike Championship and the funny thing is both the winner and the runner up are Indonesian 🇮🇩.

On the last night, Apple also invited the Weezers to the WWDC Bash (some kind of get-together concert) where we can chill out, enjoy the concert, and play games!

#+name: fig__hiit1_image
https://cdn-images-1.medium.com/max/2250/1*AiXv107iWKkFjHNFwlXAFQ.jpeg
#+name: fig__hiit2_image
https://cdn-images-1.medium.com/max/2250/1*a3GP1NeLhRs4ZSV0wcYW9Q.jpeg
#+caption: HIIT Morning Workout, SwiftStrike, and WWDC19 Bash!
#+name: fig__hiit3_image
https://cdn-images-1.medium.com/max/2000/1*-YJKq5HbYbGyURfclQbyBw.jpeg

*** Lesson learned

Meeting all those people in Dub Dub opened my mind about how I look at myself. Never think that we’re the smartest person in the room. I actually met the person that made the La Liga iOS App and all of these things pushed me to keep striving for greatness.

Second thing, as a developer we tend to focus on highly technical things. Here, I realized that the ability to communicate with other people is essential for a developer’s success. Trying to share and communicate what we have in mind will help us a lot in our everyday life.

The third and final thing is to never, ever underestimate a person, stay humble and respect everyone.

*** Final thoughts

After all, WWDC is a networking opportunity for many people. We can always see the sessions online, but the chance to speak with random people when queueing for the line is special. We never know what a short conversation with some random guy at Dub Dub can bring us.

#+begin_quote
*Pro tip*: Bring your business card and talk to as many people as you can @ WWDC
#+end_quote

#+name: fig__friends1_image
https://cdn-images-1.medium.com/max/8064/1*d2QcqQotYDs202ALyQAdqg.jpeg
#+name: fig__friends2_image
https://cdn-images-1.medium.com/max/8064/1*vX4kZveZpYSZ4W9krHvhFw.jpeg
#+name: fig__friends3_image
https://cdn-images-1.medium.com/max/8064/1*jr4w2Xikvy-La1rBAEWq2g.jpeg
#+caption: Don't be shy and make new friends @ WWDC
#+name: fig__friends4_image
https://cdn-images-1.medium.com/max/8064/1*Jo4PpChs5Mev8yYoKoAQng.jpeg

This article can’t 100% express how I felt before and after WWDC, but I hope this will inspire many people to find their way to WWDC.

Hope to see more of Indonesians (especially **HMIF ITB**) @ Dub Dub 2020!

**** Links

- [[https://github.com/abrampers/WWDC19-Submission][My WWDC19 Submission]]
- [[https://www.youtube.com/watch?v=Ry0ezsPNt6I][YouTube video]]

**** References

- Pictures by [[https://twitter.com/SwapnanilDhol][@SwapnanilDhol]] and Apple
** TODO Intercepting HTTP/2 Packets without Wireshark
:PROPERTIES:
:EXPORT_FILE_NAME: intercepting-http-2-packets-without-wireshark
:END:
#+toc: headlines 1 local

*** HTTP/2, what is it?

I never knew HTTP/2 until I bumped into gRPC, which uses HTTP/2 as its Layer 7 protocol. At first, it seems that HTTP/2 is just like another update of the commonly used HTTP/1.1. Yet HTTP/2 is a new HTTP protocol designed to deal with the limitations of HTTP/1.1.

For a bit of context, HTTP/1.1 had plenty of latency and inefficiency issues that made the performance of common internet webpage (that relies heavily on HTTP protocols) extremely hard to optimize. The first time we open a web page, it usually requires requesting a dozen resources from stylesheets, images, JavaScript codes, and other API calls. HTTP/1.1 does this by creating an equal number of TCP connection to get the resources in a parallel fashion. This means when the server is processing and preparing the response, the TCP connection is doing nothing but waiting for the server to give the response. This is very inefficient considering every single TCP connection made is doing nothing for some time. Plus there is always a cost when opening a TCP connection and closing it. So it is very inefficient to use one TCP connection per HTTP request.

HTTP/2 was made to solve some of the problems by enabling TCP to be multiplexed for multiple HTTP requests. So with HTTP/2, we will be opening less number of TCP connections compared to HTTP/1.1. HTTP/2 also enables a TCP connection to be reused for multiple request, no more one TCP connection per HTTP request. These two features will improve the utilization of the TCP connection.

Another main difference of HTTP/2 and HTTP/1.1 is that HTTP/2 is binary, while HTTP/1.1 is textual. On one hand, this gives us the benefit of speed since computers are good with binaries. Yet on the other hand, it is more difficult to debug since humans are not very good with binaries. To add on, what's more interesting is even the HTTP/2 headers are compressed for performance reasons. These two features increase the complexity to intercept and process HTTP/2 packets from the previous HTTP/1.1 where we could just read the whole payload text.

Aside from features mentioned above, there are plenty of other features of HTTP/2 you can read in the [[https://httpwg.org/specs/rfc7540.html][RFC 7540]] document.

*** Intercepting the actual packets

At this time of writing, I haven't found any way to intercept and decode HTTP/2 packet other than [[https://www.wireshark.org][Wireshark]]. Wireshark is obviously a great tool for network analysis, but at other times, we want to intercept and process the packet built in right onto our applications. In this use case, Wireshark is not a suitable option, so we need to integrate HTTP/2 into existing packet interception library.

To intercept the packets, I will be using Go with Google's [[https://github.com/google/gopacket][gopacket]]. This stack is my go to choice because Go have the first class support for HTTP and HTTP2 and Gopacket itself is fairly extensible.

From here onwards we'll use the term "frame" to represent the unit of transfer of an HTTP/2 traffic.

**** Implementing the layers

Since Gopacket doesn't support HTTP/2 as its application layer, we need to tell Gopacket about the structure of HTTP/2 frame using the code below.

#+begin_src go

// Create a layer type and give it a name and a decoder to use.
var LayerTypeHTTP2 = gopacket.RegisterLayerType(12345, gopacket.LayerTypeMetadata{Name: "HTTP2", Decoder: gopacket.DecodeFunc(decodeHTTP2)})

type HTTP2 struct {
    layers.BaseLayer

    frames []http2.Frame
}

// Implement layer's metadata
func (h HTTP2) LayerType() gopacket.LayerType      { return LayerTypeHTTP2 }
func (h *HTTP2) Payload() []byte                   { return nil }
func (h *HTTP2) CanDecode() gopacket.LayerClass    { return LayerTypeHTTP2 }
func (h *HTTP2) NextLayerType() gopacket.LayerType { return gopacket.LayerTypeZero }

// Implement the decoder function to be used
func decodeHTTP2(data []byte, p gopacket.PacketBuilder) error {
    h := &HTTP2{}
    err := h.DecodeFromBytes(data, p)
    if err != nil {
        return err
    }
    p.AddLayer(h)
    p.SetApplicationLayer(h)
    return nil
}

func (h *HTTP2) Frames() []http2.Frame {
    return h.frames
}

func (h *HTTP2) DecodeFromBytes(data []byte, df gopacket.DecodeFeedback) error {
    var frames []http2.Frame
    frameHeaderLength := uint32(9)
    payloadLength := len(data)

    payloadIdx := 0
    for payloadIdx < payloadLength {
        if payloadIdx+int(frameHeaderLength) > payloadLength {
            return fmt.Errorf("Payload length couldn't contain Frame Headers")
        }

        framePayloadLength := (uint32(data[payloadIdx+0])<<16 | uint32(data[payloadIdx+1])<<8 | uint32(data[payloadIdx+2]))
        frameLength := int(frameHeaderLength + framePayloadLength)

        rBit := data[payloadIdx+5] >> 7

        if rBit != 0 {
            return fmt.Errorf("R bit is not unset")
        }

        if payloadIdx+frameLength > payloadLength {
            return fmt.Errorf("Payload length couldn't contain Payload with the length mentioned in Frame Header")
        }

        var framerOutput bytes.Buffer
        r := bytes.NewReader(data[payloadIdx : payloadIdx+frameLength])
        framer := http2.NewFramer(&framerOutput, r)

        frame, err := framer.ReadFrame()
        if err != nil {
            return err
        }
        frames = append(frames, frame)

        payloadIdx += int(frameLength)
    }

    if payloadIdx != payloadLength {
        return fmt.Errorf("Payload length is not equal with the Frame length mentioned in Frame Header")
    }

    h.BaseLayer = layers.BaseLayer{Contents: data[:len(data)]}
    h.frames = frames
    return nil
}

#+end_src

After multiple trials, I found out that =http2.Framer= would get stuck if we give a data that's not a valid HTTP/2 frame format (as depicted below). This means we need to find a way to classify whether the bytes of data is a valid frame or not. [[https://httpwg.org/specs/rfc7540.html][RFC 7540]] document doesn't mention any way to classify a HTTP/2 frame, so I came up with a currently working solution by checking:

- Is the frame length specified in the frame header the same with the actual payload length?
- Is the R bit is unset?

#+begin_src

+-----------------------------------------------+
|                 Length (24)                   |
+---------------+---------------+---------------+
|   Type (8)    |   Flags (8)   |
+-+-------------+---------------+-------------------------------+
|R|                 Stream Identifier (31)                      |
+=+=============================================================+
|                   Frame Payload (0...)                      ...
+---------------------------------------------------------------+

#+end_src


After we check the validity of the frame, we want to utilize Go's =net/http2= package to decode the frame for us. We do that by creating a new =framer= and pass the data to the =framer=. Next we call the =ReadFrame= function to get the actual HTTP/2 frame.

**** Intercepting the frames

Next, we're going to capture the packet and decode the HTTP/2 frames.

#+begin_src go

package main

import (
    "bytes"
    "fmt"
    "log"
    "time"

    "github.com/google/gopacket"
    "github.com/google/gopacket/layers"
    "github.com/google/gopacket/pcap"

    "golang.org/x/net/http2"
)

var (
    device       string        = "lo0"
    snapshot_len int32         = 1024
    promiscuous  bool          = false
    timeout      time.Duration = 900 * time.Millisecond
    filter       string        = "tcp"
)

func main() {
    // Open device: We could also use other options (i.e. Open a .pcap file)
    handle, err := pcap.OpenLive(device, snapshot_len, promiscuous, timeout)
    if err != nil {
        log.Fatal(err)
    }
    log.Printf("Successfully opened live sniffing on %s\n", device)
    defer handle.Close()

    var h2c HTTP2

    // Create a parser to decode our HTTP/2 frame
    parser := gopacket.NewDecodingLayerParser(LayerTypeHTTP2, &h2c)

    // Use the handle as a packet source to process all packets
    source := gopacket.NewPacketSource(handle, handle.LinkType())
    decoded := []gopacket.LayerType{}

    // Process every packet
    for packet := range source.Packets() {
        ipLayer := packet.NetworkLayer()
        if ipLayer == nil {
            log.Println("No IP")
            continue
        }

        // Cast the layer to either IPv4 or IPv6
        ipv4, ipv4Ok := ipLayer.(*layers.IPv4)
        ipv6, ipv6Ok := ipLayer.(*layers.IPv6)
        if !ipv4Ok && !ipv6Ok {
            log.Println("Failed to cast packet to IPv4 or IPv6")
            continue
        }

        tcpLayer := packet.Layer(layers.LayerTypeTCP)
        if tcpLayer == nil {
            log.Println("Not a TCP Packet")
            continue
        }

        tcp, ok := tcpLayer.(*layers.TCP)
        if !ok {
            log.Println("Failed to cast packet to TCP")
            continue
        }

        appLayer := packet.ApplicationLayer()
        if appLayer == nil {
            log.Println("No ApplicationLayer payload")
            continue
        }

        packetData := appLayer.Payload()
        if err := parser.DecodeLayers(packetData, &decoded); err != nil {
            fmt.Printf("Could not decode layers: %v\n", err)
            continue
        }

        fmt.Println("*****************************************************")
        if ipv4Ok {
            fmt.Println("IPv4 SrcIP:        ", ipv4.SrcIP)
            fmt.Println("IPv4 DstIP:        ", ipv4.DstIP)
        } else if ipv6Ok {
            fmt.Println("IPv6 SrcIP:        ", ipv6.SrcIP)
            fmt.Println("IPv6 DstIP:        ", ipv6.DstIP)
        }
        fmt.Println("TCP srcPort:       ", tcp.SrcPort)
        fmt.Println("TCP dstPort:       ", tcp.DstPort)
        fmt.Println("HTTP/2:            ", h2c.frame)
        fmt.Println("*****************************************************")
    }
}

#+end_src

*** Conclusion

Using Go's native HTTP support and Gopacket, we could build a packet interception program for HTTP/2. For further HTTP/2 header processing, we could also use =net/http2/hpack= package to do the HPACK decoding and encoding.
* Footnotes
* COMMENT Local Variables                          :ARCHIVE:

# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
